### ISSUE TITLE
'NoneType' object has no attribute 'minion_type'

### ISSUE THREAD

**Issue by Ragowit** [danielyule/hearthbreaker#102]
Deck 1: Maexxna, Darkscale Healer, Silverback Patriarch, Novice Engineer, Shattered Sun Cleric, Imp Master, Gelbin Mekkatorque, Dragonling Mechanic, Water Elemental, River Crocolisk, War Golem, Frostwolf Warlord, Azure Drake, Dancing Swords, Cult Master, Mechanical Yeti, Frostwolf Warlord, Stormpike Commando, Silvermoon Guardian, Frostwolf Grunt, Flamecannon, Flamecannon, Wisp, Murloc Raider, Chillwind Yeti, Defender of Argus, Razorfen Hunter, River Crocolisk, Elven Archer, Reckless Rocketeer

Deck 2: Murloc Warleader, Murloc Tidecaller, Tirion Fordring, Secretkeeper, Loatheb, Magma Rager, Gelbin Mekkatorque, Illidan Stormrage, Murloc Raider, Maexxna, Boulderfist Ogre, Jungle Panther, Humility, Junkbot, Ancient Watcher, Target Dummy, Jungle Panther, Ogre Magi, Unstable Ghoul, Venture Co. Mercenary, Stonetusk Boar, Ironforge Rifleman, Target Dummy, Echoing Ooze, Redemption, Wolfrider, Old Murk-Eye, Muster for Battle, Feugen, Big Game Hunter

```
Traceback (most recent call last):
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\uct.py", line 159, in DoMove
    self.game.play_card(self.game.current_player.hand[move[3]])
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\engine.py", line 248, in play_card
    self.current_player.trigger("card_played", card, card_index)
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\game_objects.py", line 130, in trigger
    handler[0](*args)
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\tags\base.py", line 485, in _find_target
    if not tag.do(self.owner, focus, other):
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\tags\base.py", line 539, in do
    action.act(owner, t, other)
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\tags\action.py", line 138, in act
    card.summon(target, target.game, index)
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\cards\base.py", line 318, in summon
    minion.add_to_board(index)
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\game_objects.py", line 856, in add_to_board
    if aura.match(minion):
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\tags\base.py", line 68, in match
    self.selector.match(self.owner, obj)
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\tags\selector.py", line 315, in match
    and self.condition.evaluate(source, obj)
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\tags\condition.py", line 218, in evaluate
    return minion.card.minion_type == self.minion_type
AttributeError: 'NoneType' object has no attribute 'minion_type'
```

**Comment by Ragowit** [comment]
Closed with 195b179862ef567565f7bd7decec02de818d4209.
