### ISSUE TITLE
'NoneType' object has no attribute 'game' (calculate_stat)

### ISSUE THREAD

**Issue by Ragowit** [danielyule/hearthbreaker#103]
Deck 1: Novice Engineer, Silverback Patriarch, Novice Engineer, Silverback Patriarch, Questing Adventurer, Undertaker, Oasis Snapjaw, Water Elemental, Dalaran Mage, Mana Wyrm, Nightblade, Spiteful Smith, Deathlord, Silvermoon Guardian, Mechanical Yeti, Nightblade, Boulderfist Ogre, Fen Creeper, Frostwolf Grunt, Flamecannon, Flamecannon, Southsea Deckhand, Murloc Raider, Gnomish Inventor, Azure Drake, Shattered Sun Cleric, Dalaran Mage, Elven Archer, Stormwind Champion, Ironfur Grizzly

Deck 2: Argent Squire, Burly Rockjaw Trogg, Hogger, Micro Machine, Ancient Brewmaster, Execute, Molten Giant, Youthful Brewmaster, Ogre Brute, Clockwork Gnome, Arathi Weaponsmith, Raid Leader, Illuminator, Mana Wraith, Elven Archer, Enhance-o Mechano, Raid Leader, Azure Drake, Hobgoblin, Junkbot, Whirlwind, Cruel Taskmaster, Enhance-o Mechano, Dread Corsair, Mad Scientist, Mechwarper, Heroic Strike, Jeeves, Stormwind Knight, Harrison Jones

```
Traceback (most recent call last):
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\uct.py", line 139, in DoMove
    self.game._end_turn()
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\engine.py", line 175, in _end_turn
    self.current_player.trigger("turn_ended")
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\game_objects.py", line 130, in trigger
    handler[0](*args)
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\tags\base.py", line 485, in _find_target
    if not tag.do(self.owner, focus, other):
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\tags\base.py", line 539, in do
    action.act(owner, t, other)
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\tags\action.py", line 138, in act
    card.summon(target, target.game, index)
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\cards\base.py", line 319, in summon
    player.trigger("minion_placed", minion)
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\game_objects.py", line 130, in trigger
    handler[0](*args)
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\tags\base.py", line 365, in __action__
    if self.condition.evaluate(self.__target__, *args):
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\tags\condition.py", line 377, in evaluate
    minion.card.calculate_stat(ChangeAttack, minion.base_attack) == self.attack_equal
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\game_objects.py", line 197, in calculate_stat
    for player in self.player.game.players
AttributeError: 'NoneType' object has no attribute 'game'
```

**Comment by Ragowit** [comment]
Fixed with 574c7a6ec1123918e9aef8505cf2aa841c258bd6.
