### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Ragowit** [danielyule/hearthbreaker#105]
Deck 1: Darkscale Healer, Feugen, Darkscale Healer, Silverback Patriarch, Novice Engineer, Shattered Sun Cleric, Antique Healbot, Jungle Panther, Duplicate, Dragonling Mechanic, Water Elemental, River Crocolisk, Ice Lance, Gurubashi Berserker, Fen Creeper, Dancing Swords, Defender of Argus, Ship's Cannon, Gurubashi Berserker, Archmage, Azure Drake, Frostwolf Grunt, Flamecannon, Flamecannon, Argent Squire, Murloc Raider, Chillwind Yeti, Silvermoon Guardian, Razorfen Hunter, River Crocolisk

Deck 2: Nightblade, Priestess of Elune, Abusive Sergeant, Doomsayer, Loatheb, Starving Buzzard, Sunwalker, Tracking, Gelbin Mekkatorque, Stormpike Commando, Bloodsail Corsair, Youthful Brewmaster, Pint-Sized Summoner, Captain's Parrot, Savannah Highmane, Gazlowe, Nozdormu, Murloc Warleader, Raid Leader, Injured Blademaster, Fel Reaver, Ancient Brewmaster, Target Dummy, Master Swordsmith, Murloc Warleader, Cairne Bloodhoof, Windfury Harpy, Stormwind Champion, Hungry Crab, Gnomish Experimenter

```
Traceback (most recent call last):
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\uct.py", line 181, in DoMove
    self.game.play_card(self.game.current_player.hand[move[3]])
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\engine.py", line 255, in play_card
    card.use(self.current_player, self)
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\cards\base.py", line 281, in use
    if not battlecry.do(minion, minion):
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\tags\base.py", line 531, in do
    if not self.condition.evaluate(owner, target):
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\tags\condition.py", line 482, in evaluate
    return all([self.condition.evaluate(target, t, *args) for t in self.selector.get_targets(target, *args)])
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\tags\selector.py", line 161, in get_targets
    return [player.hand[-1] for player in players]
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\tags\selector.py", line 161, in <listcomp>
    return [player.hand[-1] for player in players]
IndexError: list index out of range
```

**Comment by Ragowit** [comment]
Just by looking at the cards in each deck, I would guess it's Captain's Parrot that is the problem.

**Comment by Ragowit** [comment]
Seems to be Gnomish Experimenter. The problem occurs when the player have no cards left in the deck and at the same time no cards in hand. Gnomish triggers draw, which doesn't draw anything, and then the program tries to look at the latest card in hand that doesn't exist.

So if you still have cards in hand, no error occur but the wrong card is being returned (no card should be returned).
