### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'game' (Secrets)

### ISSUE THREAD

**Issue by Ragowit** [danielyule/hearthbreaker#106]
Sadly, I have no deck information for this issue.

```
Traceback (most recent call last):
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\uct.py", line 641, in <module>
    UCTPlayGame()
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\uct.py", line 624, in UCTPlayGame
    m = UCT(rootstate = state, seconds = 12000, verbose = False)
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\uct.py", line 594, in UCT
    while state.GetMoves() != []: # while state is non-terminal
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\uct.py", line 407, in GetMoves
    if card.can_use(self.game.current_player, self.game) and isinstance(card, MinionCard):
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\cards\base.py", line 491, in can_use
    return super().can_use(player, game) and self.name not in [secret.name for secret in player.secrets]
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\cards\base.py", line 103, in can_use
    return player.mana >= self.mana_cost(player)
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\cards\base.py", line 121, in mana_cost
    for p in self.player.game.players
AttributeError: 'NoneType' object has no attribute 'game'
```

**Comment by Ragowit** [comment]
Probably a secret card that didn't get an .attach() somewhere.

**Comment by Ragowit** [comment]
Deck 1: Wolfrider, Duplicate, Dancing Swords, Darkscale Healer, Silverback Patriarch, Novice Engineer, Shattered Sun Cleric, Stonesplinter Trogg, Imp Master, Gelbin Mekkatorque, Dragonling Mechanic, Water Elemental, River Crocolisk, War Golem, Frostwolf Warlord, Azure Drake, Dancing Swords, Cult Master, Ship's Cannon, Frostwolf Warlord, Stormpike Commando, Silvermoon Guardian, Frostwolf Grunt, Flamecannon, Flamecannon, Wisp, Murloc Raider, Chillwind Yeti, Defender of Argus, Razorfen Hunter

Deck 2: Spectral Knight, Tinkertown Technician, Boulderfist Ogre, Silvermoon Guardian, Dragonling Mechanic, Master Swordsmith, Loatheb, Young Priestess, Argent Squire, Wolfrider, Venture Co. Mercenary, Southsea Deckhand, Pint-Sized Summoner, Twilight Drake, Zombie Chow, Tinkertown Technician, Micro Machine, Injured Blademaster, Kel'Thuzad, Cogmaster, Bloodmage Thalnos, Mekgineer Thermaplugg, Flesheating Ghoul, Duplicate, Spellbender, Blingtron 3000, Vaporize, Coldlight Oracle, Shattered Sun Cleric, Snowchugger
