### ISSUE TITLE
'NoneType' object has no attribute 'game'

### ISSUE THREAD

**Issue by Ragowit** [danielyule/hearthbreaker#107]
It's still around...

Deck 1: Stranglethorn Tiger, Haunted Creeper, Zombie Chow, Darkscale Healer, Silverback Patriarch, Novice Engineer, Shattered Sun Cleric, Stonesplinter Trogg, Imp Master, Gelbin Mekkatorque, Dragonling Mechanic, Water Elemental, River Crocolisk, War Golem, Frostwolf Warlord, Azure Drake, Dancing Swords, Cult Master, Puddlestomper, Frostwolf Warlord, Stormpike Commando, Silvermoon Guardian, Frostwolf Grunt, Kel'Thuzad, Flamecannon, Wisp, Murloc Raider, Chillwind Yeti, Defender of Argus, Razorfen Hunter

Deck 2: Mechwarper, Nerub'ar Weblord, Unstable Ghoul, Ice Lance, Injured Blademaster, Wee Spellstopper, Sorcerer's Apprentice, Mirror Image, Sen'jin Shieldmasta, Youthful Brewmaster, Core Hound, Archmage Antonidas, Explosive Sheep, Arcane Missiles, Hogger, Nerub'ar Weblord, Leper Gnome, Echo of Medivh, Raging Worgen, Pyroblast, Water Elemental, Unstable Ghoul, Maexxna, Old Murk-Eye, Lightwarden, Kezan Mystic, Spellbreaker, Imp Master, Blood Knight, Gnomish Inventor

```
Traceback (most recent call last):
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\uct.py", line 408, in GetMoves
    if card.can_use(self.game.current_player, self.game) and isinstance(card, MinionCard):
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\cards\base.py", line 226, in can_use
    return len(player.minions) < 7 and super().can_use(player, game)
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\cards\base.py", line 103, in can_use
    return player.mana >= self.mana_cost(player)
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\cards\base.py", line 121, in mana_cost
    for p in self.player.game.players
AttributeError: 'NoneType' object has no attribute 'game'
```

**Comment by Ragowit** [comment]
Fixed with b80df04cdcfddebaa7ea389714faab2c88ad6dc5.
