### ISSUE TITLE
Buff not in list

### ISSUE THREAD

**Issue by Ragowit** [danielyule/hearthbreaker#75]
Deck 1: Nightblade, Arcane Shot, Hunter's Mark, Hunter's Mark, Darkscale Healer, Kill Command, Kill Command, Multi-Shot, Arcane Shot, Demolisher, Timber Wolf, Timber Wolf, Tracking, Murloc Tidehunter, Tracking, Stormpike Commando, Animal Companion, Animal Companion, Murloc Tidehunter, Ironbeak Owl, Shattered Sun Cleric, Shattered Sun Cleric, Reckless Rocketeer, Razorfen Hunter, Gelbin Mekkatorque, Frostwolf Warlord, Silverback Patriarch, Core Hound, Mad Scientist, War Golem

Deck 2: Faceless Manipulator, Faceless Manipulator, Blessing of Might, Noble Sacrifice, Loot Hoarder, Silver Hand Knight, Silvermoon Guardian, Haunted Creeper, Haunted Creeper, Kel'Thuzad, Southsea Deckhand, Spiteful Smith, Bloodfen Raptor, Reckless Rocketeer, Eye for an Eye, Nat Pagle, Deathwing, Mad Scientist, Flesheating Ghoul, Flesheating Ghoul, Silverback Patriarch, Silverback Patriarch, Lord of the Arena, Coldlight Seer, Gadgetzan Auctioneer, Stoneskin Gargoyle, Sunwalker, Clockwork Gnome, Windfury Harpy, Sea Giant

```
Traceback (most recent call last):
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\uct.py", line 128, in DoMove
    self.game._start_turn()
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\game_objects.py", line 1934, in _start_turn
    self.current_player.trigger("turn_started")
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\game_objects.py", line 171, in trigger
    handler[0](*args)
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\tags\base.py", line 99, in __until__
    self.owner.remove_buff(self)
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\game_objects.py", line 332, in remove_buff
    self.buffs.remove(buff)
ValueError: list.remove(x): x not in list
```

**Comment by Ragowit** [comment]
Got this error again.

Deck 1: Frost Shock, Ancestral Healing, Ancestral Healing, Shattered Sun Cleric, Frost Shock, Rockbiter Weapon, Totemic Might, Flametongue Totem, Windfury, Reckless Rocketeer, Totemic Might, Flametongue Totem, Reckless Rocketeer, Wisp, Rockbiter Weapon, Stonetusk Boar, Windfury, Hex, Oasis Snapjaw, Elven Archer, Hex, Bluegill Warrior, Reincarnate, Nerub'ar Weblord, Unstable Ghoul, Goldshire Footman, Bloodlust, Raid Leader, Windspeaker, Goldshire Footman

Deck 2: Snipe, Fen Creeper, Baron Geddon, Sea Giant, Ysera, Tracking, Cobra Shot, Bloodmage Thalnos, Illidan Stormrage, Scavenging Hyena, Boulderfist Ogre, Zombie Chow, The Black Knight, Burly Rockjaw Trogg, Captain Greenskin, Echoing Ooze, The Beast, Frostwolf Grunt, Frostwolf Grunt, Elite Tauren Chieftain, Timber Wolf, Stormpike Commando, Timber Wolf, Stormpike Commando, Tundra Rhino, Tundra Rhino, Crazed Alchemist, Crazed Alchemist, Molten Giant, Molten Giant

```
Traceback (most recent call last):
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\uct.py", line 117, in DoMove
    self.game._end_turn()
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\game_objects.py", line 1941, in _end_turn
    self.current_player.trigger("turn_ended")
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\game_objects.py", line 171, in trigger
    handler[0](*args)
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\tags\base.py", line 99, in __until__
    self.owner.remove_buff(self)
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\game_objects.py", line 332, in remove_buff
    self.buffs.remove(buff)
ValueError: list.remove(x): x not in list
```

**Comment by Ragowit** [comment]
And again, new decks to try:

Deck 1: Novice Engineer, Execute, Lord of the Arena, Execute, Archmage, Whirlwind, Whirlwind, Arcanite Reaper, Shield Block, Kobold Geomancer, Kobold Geomancer, Heroic Strike, Ogre Magi, Mechwarper, Boulderfist Ogre, Dragonling Mechanic, Ironforge Rifleman, Chillwind Yeti, Cult Master, Haunted Creeper, Ogre Magi, Elven Archer, Ironfur Grizzly, Brawl, Archmage, Death's Bite, Loatheb, Stranglethorn Tiger, Boulderfist Ogre, Core Hound

Deck 2: Defender of Argus, Big Game Hunter, Stoneskin Gargoyle, Sea Giant, Argent Squire, Azure Drake, Dark Iron Dwarf, Lorewalker Cho, Mana Wyrm, Worgen Infiltrator, Dalaran Mage, Gadgetzan Auctioneer, Frostbolt, Ragnaros the Firelord, Windfury Harpy, Bloodsail Corsair, Stampeding Kodo, Gnomish Inventor, Shieldbearer, Dread Corsair, Undertaker, Sen'jin Shieldmasta, Priestess of Elune, Spellbender, Murloc Raider, The Beast, Molten Giant, Ice Block, Dragonling Mechanic, Ancient Brewmaster
