### ISSUE TITLE
That card cannot be used

### ISSUE THREAD

**Issue by Ragowit** [danielyule/hearthbreaker#76]
Deck 1: Ironforge Rifleman, Wolfrider, Grimscale Oracle, Grimscale Oracle, Acidic Swamp Ooze, Wolfrider, Starving Buzzard, Hunter's Mark, Arcane Shot, Timber Wolf, Hunter's Mark, Arcane Shot, Starving Buzzard, Timber Wolf, Acidic Swamp Ooze, Tracking, Tracking, Houndmaster, Lord of the Arena, Animal Companion, Houndmaster, Kill Command, Bluegill Warrior, Tundra Rhino, Animal Companion, Goldshire Footman, Kill Command, Tundra Rhino, Core Hound, Multi-Shot

Deck 2: Harrison Jones, Clockwork Giant, Zombie Chow, Magma Rager, Harvest Golem, Sunfury Protector, Ironfur Grizzly, Gnomish Inventor, Captain's Parrot, Cult Master, Knife Juggler, Mark of the Wild, Youthful Brewmaster, Ancient of Lore, Gruul, Gurubashi Berserker, Bluegill Warrior, Shieldbearer, Ysera, Stormpike Commando, Bloodsail Corsair, Savagery, Savagery, Priestess of Elune, Priestess of Elune, Razorfen Hunter, Bomb Lobber, Razorfen Hunter, Unstable Ghoul, Thrallmar Farseer

```
Move: ['summon_minion', <hearthbreaker.cards.minions.hunter.TimberWolf object at 0x00000000041ABF98>, None, 2, 0, 0]

Hand Player 0: [<hearthbreaker.cards.spells.hunter.KillCommand object at 0x0000000004461550>, <hearthbreaker.cards.spells.hunter.HuntersMark object at 0x0000000004461198>, <hearthbreaker.cards.spells.hunter.HuntersMark object at 0x0000000004461FD0>, <hearthbreaker.cards.minions.hunter.TimberWolf object at 0x0000000004461898>]

Hand Player 1: [<hearthbreaker.cards.minions.neutral.SunfuryProtector object at 0x000000000575D278>, <hearthbreaker.cards.minions.neutral.CaptainsParrot object at 0x000000000575DEF0>, <hearthbreaker.cards.minions.neutral.BloodsailCorsair object at 0x000000000575DEB8>, <hearthbreaker.cards.minions.neutral.PriestessOfElune object at 0x000000000575D2B0>, <hearthbreaker.cards.TheCoin object at 0x0000000004461EB8>]


Traceback (most recent call last):
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\uct.py", line 148, in DoMove
    self.game.play_card(self.game.current_player.hand[move[3]])
  File "C:\Users\Ragowit\Documents\GitHub\mcts\hearthbreaker\hearthbreaker\game_objects.py", line 2004, in play_card
    raise GameException("That card cannot be used")
hearthbreaker.game_objects.GameException: That card cannot be used
```

**Comment by Ragowit** [comment]
Thank you for looking into this and helping me out. I'll continue to work on this on my fork.
