### ISSUE TITLE
'MirrorImage' object has no attribute 'summon'

### ISSUE THREAD

**Issue by Ragowit** [danielyule/hearthbreaker#81]
Deck 1: Fire Elemental, Stonetusk Boar, Fire Elemental, Windfury, River Crocolisk, Loot Hoarder, Stormpike Commando, Ancestral Spirit, Wolfrider, River Crocolisk, Wolfrider, Azure Drake, Nerub'ar Weblord, Ogre Magi, Bloodlust, Ironforge Rifleman, Argent Squire, Stormpike Commando, Zombie Chow, Loatheb, Gelbin Mekkatorque, Archmage, Lord of the Arena, Undertaker, Kobold Geomancer, Ironbeak Owl, Stonetusk Boar, Ogre Magi, Zombie Chow, Chillwind Yeti

Deck 2: Mana Wyrm, Harrison Jones, Antique Healbot, Sen'jin Shieldmasta, Mirror Entity, Leeroy Jenkins, Coldlight Seer, Injured Blademaster, Unstable Ghoul, Bloodsail Corsair, Blood Knight, Arcane Golem, Spider Tank, Bomb Lobber, Stoneskin Gargoyle, Feugen, Gruul, Blingtron 3000, Zombie Chow, Thrallmar Farseer, Earthen Ring Farseer, Defender of Argus, Violet Teacher, Counterspell, Mechanical Yeti, Violet Teacher, Shade of Naxxramas, Bluegill Warrior, Ironforge Rifleman, Mirror Image

```
Traceback (most recent call last):
  File "C:\Users\Markus\git\hearthbreaker\uct.py", line 175, in DoMove
    self.game.current_player.minions[move[3]].attack()
  File "C:\Users\Markus\git\hearthbreaker\hearthbreaker\game_objects.py", line 1165, in attack
    super().attack()
  File "C:\Users\Markus\git\hearthbreaker\hearthbreaker\game_objects.py", line 386, in attack
    self.player.game.check_delayed()
  File "C:\Users\Markus\git\hearthbreaker\hearthbreaker\game_objects.py", line 1857, in check_delayed
    minion.activate_delayed()
  File "C:\Users\Markus\git\hearthbreaker\hearthbreaker\game_objects.py", line 440, in activate_delayed
    self.trigger(delayed['event'], *delayed['args'])
  File "C:\Users\Markus\git\hearthbreaker\hearthbreaker\game_objects.py", line 171, in trigger
    handler[0](*args)
  File "C:\Users\Markus\git\hearthbreaker\hearthbreaker\game_objects.py", line 1186, in delayed_death
    rattle.deathrattle(self)
  File "C:\Users\Markus\git\hearthbreaker\hearthbreaker\tags\base.py", line 476, in deathrattle
    self.action.act(target, t)
  File "C:\Users\Markus\git\hearthbreaker\hearthbreaker\tags\action.py", line 170, in act
    card.summon(target, target.game, index)
AttributeError: 'MirrorImage' object has no attribute 'summon'
```

**Comment by Ragowit** [comment]
I believe this issue is becuase of "Mirror Image" spell vs minion.

It tries to lookup Mirror Image and get the spell instead of minion, this is because of:
1) Only the spell is listed in the get_card() list.
2) Even if we move MirrorImageMinion() from MirrorImage to minions.mage so do they still have the same name, should we name it differently ("Mirror Image Minion")? Or change the way get_card() works?

**Comment by danielyule** [comment]
Turns out, I had already fixed the way get_card() works, but I hadn't fixed Mirror Image to work with it.
