### ISSUE TITLE
'Spellbender' object has no attribute 'summon'

### ISSUE THREAD

**Issue by Ragowit** [danielyule/hearthbreaker#82]
Deck 1: Elven Archer, Chillwind Yeti, Defender of Argus, Knife Juggler, Sludge Belcher, River Crocolisk, Mad Scientist, Darkscale Healer, Silverback Patriarch, Novice Engineer, Shattered Sun Cleric, Cult Master, Echoing Ooze, Dragonling Mechanic, Bloodlust, River Crocolisk, Ancestral Spirit, Gurubashi Berserker, Gelbin Mekkatorque, Wailing Soul, Spiteful Smith, Gurubashi Berserker, Archmage, Frost Elemental, Frostwolf Grunt, Dire Wolf Alpha, Murloc Raider, Dragonling Mechanic, Frost Elemental, Shattered Sun Cleric

Deck 2: Shieldbearer, Maexxna, Goldshire Footman, Clockwork Giant, Cult Master, Mana Wyrm, Ice Block, Kobold Geomancer, Tinkmaster Overspark, Angry Chicken, Sunfury Protector, Amani Berserker, Reckless Rocketeer, Archmage Antonidas, Young Dragonhawk, Defender of Argus, Spellbender, Cairne Bloodhoof, Dark Iron Dwarf, Vaporize, War Golem, Chillwind Yeti, Spectral Knight, Arcane Missiles, Spiteful Smith, Spectral Knight, Grimscale Oracle, Gnomish Inventor, Lightwarden, Kobold Geomancer

```
Traceback (most recent call last):
  File "C:\Users\Markus\git\hearthbreaker\uct.py", line 175, in DoMove
    self.game.current_player.minions[move[3]].attack()
  File "C:\Users\Markus\git\hearthbreaker\hearthbreaker\game_objects.py", line 1165, in attack
    super().attack()
  File "C:\Users\Markus\git\hearthbreaker\hearthbreaker\game_objects.py", line 386, in attack
    self.player.game.check_delayed()
  File "C:\Users\Markus\git\hearthbreaker\hearthbreaker\game_objects.py", line 1857, in check_delayed
    minion.activate_delayed()
  File "C:\Users\Markus\git\hearthbreaker\hearthbreaker\game_objects.py", line 440, in activate_delayed
    self.trigger(delayed['event'], *delayed['args'])
  File "C:\Users\Markus\git\hearthbreaker\hearthbreaker\game_objects.py", line 171, in trigger
    handler[0](*args)
  File "C:\Users\Markus\git\hearthbreaker\hearthbreaker\game_objects.py", line 1186, in delayed_death
    rattle.deathrattle(self)
  File "C:\Users\Markus\git\hearthbreaker\hearthbreaker\tags\base.py", line 476, in deathrattle
    self.action.act(target, t)
  File "C:\Users\Markus\git\hearthbreaker\hearthbreaker\tags\action.py", line 170, in act
    card.summon(target, target.game, index)
AttributeError: 'Spellbender' object has no attribute 'summon'
```

**Comment by Ragowit** [comment]
I believe this error is the same as the Mirror Image one we just had. Spellbender secret is triggered, Spellbender minion is summoned. Gets bounced and get_card() finds the secret instead of minion.
