### ISSUE TITLE
The AI tries to play unplayable cards

### ISSUE THREAD

**Issue by anka-213** [danielyule/hearthbreaker#93]
I was trying to play a game (using text_runner.py) where the AI had a deck consisting of only Misdirection and my deck only having Ogre Brute, but it keeps crashing with the error:

    hearthbreaker.game_objects.GameException: That card cannot be used

My guess is that the AI tries to play the same secret twice.

**Comment by anka-213** [comment]
Full traceback:

```
Traceback (most recent call last):
  File "text_runner.py", line 413, in <module>
    curses.wrapper(render_game)
  File "/usr/lib/python3.4/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "text_runner.py", line 406, in render_game
    game.start()
  File "/media/shared/projects/hearthbreaker/hearthbreaker/hearthbreaker/engine.py", line 134, in start
    self.play_single_turn()
  File "/media/shared/projects/hearthbreaker/hearthbreaker/hearthbreaker/engine.py", line 138, in play_single_turn
    self.current_player.agent.do_turn(self.current_player)
  File "/media/shared/projects/hearthbreaker/hearthbreaker/hearthbreaker/agents/trade_agent.py", line 113, in do_turn
    self.play_cards(player)
  File "/media/shared/projects/hearthbreaker/hearthbreaker/hearthbreaker/agents/trade/possible_play.py", line 210, in play_cards
    card = self.play_one_card(player)
  File "/media/shared/projects/hearthbreaker/hearthbreaker/hearthbreaker/agents/trade/possible_play.py", line 205, in play_one_card
    player.game.play_card(card)
  File "/media/shared/projects/hearthbreaker/hearthbreaker/hearthbreaker/engine.py", line 230, in play_card
    raise GameException("That card cannot be used")
```

**Comment by danielyule** [comment]
You are correct, the TradeAgent was only taking the card's mana cost into account when deciding to play it, and not at all whether is was valid to play.  I've now fixed that problem.  I think the TradeAgent will need some love, as I think Venture Co might also cause some issues...
