### ISSUE TITLE
run_game.py Attribute Error

### ISSUE THREAD

**Issue by OlivierLamiraux** [danielyule/hearthbreaker#98]
Hi,
I use pypy3-2.4.0 on windows and no success to install curse on it. I have try the run_game.py script but I have some error.

PS C:\hearthbreaker-master\hearthbreaker-master> pypy .\run_games.py
Traceback (most recent call last):
  File ".\run_games.py", line 57, in <module>
    do_stuff()
  File ".\run_games.py", line 52, in do_stuff
    game = Game([deck1, deck2], [RandomAgent(), RandomAgent()])
  File "C:\hearthbreaker-master\hearthbreaker-master\hearthbreaker\engine.py", line 58, in __init__
    self.players = [Player("one", decks[play_order[0]], agents[play_order[0]], self),
  File "C:\hearthbreaker-master\hearthbreaker-master\hearthbreaker\engine.py", line 316, in __init__
    self.hero = deck.hero.create_hero(self)
AttributeError: 'int' object has no attribute 'create_hero'

**Comment by danielyule** [comment]
Hi Olivier,

Seems like curses and pypy don't work together on windows.  You could POSSIBLY compile it together yourself, but that's going to be tricky.  Hearthbreaker runs much faster on Cython anyhow.

For your other error, I've uploaded a fix that ought to solve your problem.
